// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketAPI.Models;

#nullable disable

namespace TicketAPI.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20250405204036_AddPasswordSaltColumn")]
    partial class AddPasswordSaltColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ArtistGenre", b =>
                {
                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("id_artist");

                    b.Property<int>("IdGenre")
                        .HasColumnType("int")
                        .HasColumnName("id_genre");

                    b.HasKey("IdArtist", "IdGenre")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdGenre" }, "id_genre");

                    b.ToTable("artist_genre", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Artist", b =>
                {
                    b.Property<int>("IdArtist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_artist");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdArtist"));

                    b.Property<string>("BackgroundPhotoArtist")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("background_photo_artist");

                    b.Property<string>("ColorArtist")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color_artist");

                    b.Property<string>("DescriptionArtist")
                        .HasColumnType("text")
                        .HasColumnName("description_artist");

                    b.Property<string>("NameArtist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_artist");

                    b.Property<string>("ProfilePhotoArtist")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_photo_artist");

                    b.HasKey("IdArtist")
                        .HasName("PRIMARY");

                    b.ToTable("artist", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Concert", b =>
                {
                    b.Property<int>("IdConcert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_concert");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConcert"));

                    b.Property<int?>("AgeLimitConcert")
                        .HasColumnType("int")
                        .HasColumnName("age_limit_concert");

                    b.Property<DateOnly>("DateStartConcert")
                        .HasColumnType("date")
                        .HasColumnName("date_start_concert");

                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("id_artist");

                    b.Property<int>("IdHall")
                        .HasColumnType("int")
                        .HasColumnName("id_hall");

                    b.Property<string>("StatusConcert")
                        .IsRequired()
                        .HasColumnType("enum('планируется','прошел','отменен')")
                        .HasColumnName("status_concert");

                    b.Property<TimeOnly>("TimeStartConcert")
                        .HasColumnType("time")
                        .HasColumnName("time_start_concert");

                    b.HasKey("IdConcert")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdArtist" }, "id_artist");

                    b.HasIndex(new[] { "IdHall" }, "id_hall");

                    b.ToTable("concert", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Favorite", b =>
                {
                    b.Property<int>("IdFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_favorite");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFavorite"));

                    b.Property<DateTime?>("AddedDateFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("added_date_favorite")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("id_artist");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.HasKey("IdFavorite")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdArtist" }, "id_artist")
                        .HasDatabaseName("id_artist1");

                    b.HasIndex(new[] { "IdUser" }, "id_user");

                    b.ToTable("favorite", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_genre");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGenre"));

                    b.Property<string>("ColorGenre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color_genre");

                    b.Property<string>("IconUrlGenre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("icon_url_genre")
                        .HasDefaultValueSql("''");

                    b.Property<string>("NameGenre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_genre");

                    b.HasKey("IdGenre")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NameGenre" }, "name_genre")
                        .IsUnique();

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Hall", b =>
                {
                    b.Property<int>("IdHall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_hall");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHall"));

                    b.Property<string>("BuildingHall")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("building_hall");

                    b.Property<string>("CityHall")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city_hall");

                    b.Property<string>("DescriptionHall")
                        .HasColumnType("text")
                        .HasColumnName("description_hall");

                    b.Property<string>("NameHall")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_hall");

                    b.Property<string>("StreetHall")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("street_hall");

                    b.HasKey("IdHall")
                        .HasName("PRIMARY");

                    b.ToTable("hall", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_notification");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime?>("DateNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_notification")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("id_artist");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.Property<string>("MessageNotification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_notification");

                    b.HasKey("IdNotification")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdArtist" }, "id_artist")
                        .HasDatabaseName("id_artist2");

                    b.HasIndex(new[] { "IdUser" }, "id_user")
                        .HasDatabaseName("id_user1");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Recommendation", b =>
                {
                    b.Property<int>("IdRecommendation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recommendation");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRecommendation"));

                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("id_artist");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.HasKey("IdRecommendation")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdArtist" }, "id_artist")
                        .HasDatabaseName("id_artist3");

                    b.HasIndex(new[] { "IdUser" }, "id_user")
                        .HasDatabaseName("id_user2");

                    b.ToTable("recommendation", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_review");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReview"));

                    b.Property<DateTime?>("DateReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_review")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdConcert")
                        .HasColumnType("int")
                        .HasColumnName("id_concert");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.Property<int?>("RatingReview")
                        .HasColumnType("int")
                        .HasColumnName("rating_review");

                    b.Property<string>("TextReview")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_review");

                    b.HasKey("IdReview")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdConcert" }, "id_concert");

                    b.HasIndex(new[] { "IdUser" }, "id_user")
                        .HasDatabaseName("id_user3");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_role");

                    b.HasKey("IdRole")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NameRole" }, "name_role")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Section", b =>
                {
                    b.Property<int>("IdSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_section");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSection"));

                    b.Property<int>("IdHall")
                        .HasColumnType("int")
                        .HasColumnName("id_hall");

                    b.Property<string>("NameSection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_section");

                    b.Property<decimal>("PriceSection")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_section");

                    b.Property<string>("SchemaSection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema_section");

                    b.HasKey("IdSection")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdHall" }, "id_hall")
                        .HasDatabaseName("id_hall1");

                    b.ToTable("section", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ticket");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<int>("IdConcert")
                        .HasColumnType("int")
                        .HasColumnName("id_concert");

                    b.Property<int>("IdSection")
                        .HasColumnType("int")
                        .HasColumnName("id_section");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.Property<DateTime?>("PurchaseDateTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("purchase_date_ticket")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RowTicket")
                        .HasColumnType("int")
                        .HasColumnName("row_ticket");

                    b.Property<int>("SeatTicket")
                        .HasColumnType("int")
                        .HasColumnName("seat_ticket");

                    b.Property<string>("StatusTicket")
                        .IsRequired()
                        .HasColumnType("enum('активен','использован','возвращен')")
                        .HasColumnName("status_ticket");

                    b.HasKey("IdTicket")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdConcert" }, "id_concert")
                        .HasDatabaseName("id_concert1");

                    b.HasIndex(new[] { "IdSection" }, "id_section");

                    b.HasIndex(new[] { "IdUser" }, "id_user")
                        .HasDatabaseName("id_user4");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("TicketAPI.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateOnly>("BirthDateUser")
                        .HasColumnType("date")
                        .HasColumnName("birth_date_user");

                    b.Property<string>("CityUser")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city_user");

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email_user");

                    b.Property<string>("FirstNameUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name_user");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    b.Property<string>("LastNameUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name_user");

                    b.Property<string>("LoginUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login_user");

                    b.Property<string>("PasswordHashUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash_user");

                    b.HasKey("IdUser")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmailUser" }, "email_user")
                        .IsUnique();

                    b.HasIndex(new[] { "IdRole" }, "id_role");

                    b.HasIndex(new[] { "LoginUser" }, "login_user")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ArtistGenre", b =>
                {
                    b.HasOne("TicketAPI.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("IdArtist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("artist_genre_ibfk_1");

                    b.HasOne("TicketAPI.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("artist_genre_ibfk_2");
                });

            modelBuilder.Entity("TicketAPI.Models.Concert", b =>
                {
                    b.HasOne("TicketAPI.Models.Artist", "IdArtistNavigation")
                        .WithMany("Concerts")
                        .HasForeignKey("IdArtist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("concert_ibfk_1");

                    b.HasOne("TicketAPI.Models.Hall", "IdHallNavigation")
                        .WithMany("Concerts")
                        .HasForeignKey("IdHall")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("concert_ibfk_2");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdHallNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.Favorite", b =>
                {
                    b.HasOne("TicketAPI.Models.Artist", "IdArtistNavigation")
                        .WithMany("Favorites")
                        .HasForeignKey("IdArtist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorite_ibfk_2");

                    b.HasOne("TicketAPI.Models.User", "IdUserNavigation")
                        .WithMany("Favorites")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorite_ibfk_1");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.Notification", b =>
                {
                    b.HasOne("TicketAPI.Models.Artist", "IdArtistNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdArtist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notification_ibfk_2");

                    b.HasOne("TicketAPI.Models.User", "IdUserNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notification_ibfk_1");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.Recommendation", b =>
                {
                    b.HasOne("TicketAPI.Models.Artist", "IdArtistNavigation")
                        .WithMany("Recommendations")
                        .HasForeignKey("IdArtist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recommendation_ibfk_2");

                    b.HasOne("TicketAPI.Models.User", "IdUserNavigation")
                        .WithMany("Recommendations")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recommendation_ibfk_1");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.Review", b =>
                {
                    b.HasOne("TicketAPI.Models.Concert", "IdConcertNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdConcert")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("review_ibfk_2");

                    b.HasOne("TicketAPI.Models.User", "IdUserNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("review_ibfk_1");

                    b.Navigation("IdConcertNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.Section", b =>
                {
                    b.HasOne("TicketAPI.Models.Hall", "IdHallNavigation")
                        .WithMany("Sections")
                        .HasForeignKey("IdHall")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("section_ibfk_1");

                    b.Navigation("IdHallNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.Ticket", b =>
                {
                    b.HasOne("TicketAPI.Models.Concert", "IdConcertNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdConcert")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ticket_ibfk_1");

                    b.HasOne("TicketAPI.Models.Section", "IdSectionNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdSection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ticket_ibfk_3");

                    b.HasOne("TicketAPI.Models.User", "IdUserNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ticket_ibfk_2");

                    b.Navigation("IdConcertNavigation");

                    b.Navigation("IdSectionNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.User", b =>
                {
                    b.HasOne("TicketAPI.Models.Role", "IdRoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_ibfk_1");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("TicketAPI.Models.Artist", b =>
                {
                    b.Navigation("Concerts");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("TicketAPI.Models.Concert", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketAPI.Models.Hall", b =>
                {
                    b.Navigation("Concerts");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("TicketAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TicketAPI.Models.Section", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketAPI.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Recommendations");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
